// <auto-generated />
using App_01_ServerManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_01_ServerManagement.Migrations
{
    [DbContext(typeof(ServerManagementContext))]
    [Migration("20241130041841_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_01_ServerManagement.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerId");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            City = "New York",
                            IsOnline = false,
                            Name = "SRV-NYC-01"
                        },
                        new
                        {
                            ServerId = 2,
                            City = "London",
                            IsOnline = true,
                            Name = "SRV-LAX-01"
                        },
                        new
                        {
                            ServerId = 3,
                            City = "Chicago",
                            IsOnline = true,
                            Name = "SRV-CHI-01"
                        },
                        new
                        {
                            ServerId = 4,
                            City = "London",
                            IsOnline = false,
                            Name = "SRV-LON-01"
                        },
                        new
                        {
                            ServerId = 5,
                            City = "Tokyo",
                            IsOnline = false,
                            Name = "SRV-TKY-01"
                        },
                        new
                        {
                            ServerId = 6,
                            City = "London",
                            IsOnline = false,
                            Name = "SRV-SYD-01"
                        },
                        new
                        {
                            ServerId = 7,
                            City = "Chicago",
                            IsOnline = false,
                            Name = "SRV-SIN-01"
                        },
                        new
                        {
                            ServerId = 8,
                            City = "Chicago",
                            IsOnline = false,
                            Name = "SRV-FRA-01"
                        },
                        new
                        {
                            ServerId = 9,
                            City = "Chicago",
                            IsOnline = false,
                            Name = "SRV-TOR-01"
                        },
                        new
                        {
                            ServerId = 10,
                            City = "London",
                            IsOnline = true,
                            Name = "SRV-AMS-01"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
